apiVersion: v1
kind: Service
metadata:
  name: squid-proxy-service
  namespace: squid-proxy
spec:
  selector:
    app: squid-proxy
  ports:
  - name: http
    port: 3128
    targetPort: 3128
  type: ClusterIP
