# credentials:
#   system:
#     domainCredentials:
#     - credentials:
#       - usernamePassword:
#           description: "github-pwd"
#           id: "github-pwd"
#           password: "{AQAAABAAAABA7AfoA4o8Hfy7pg0Y4bp617g3c4R91BV8boc2nwNXWjp/sUiM23UcdrnF/Ri1gflwqHIdzJ7nIPcuOBOE3le76EkKGng0zaEHilqYOk9tDVk=}"
#           scope: GLOBAL
#           username: "opeomotayo"
# jenkins:
#   agentProtocols:
#   - "JNLP4-connect"
#   - "Ping"
#   authorizationStrategy:
#     loggedInUsersCanDoAnything:
#       allowAnonymousRead: false
#   clouds:
#   - kubernetes:
#       containerCap: 10
#       containerCapStr: "10"
#       jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
#       jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
#       name: "kubernetes"
#       namespace: "jenkins"
#       podLabels:
#       - key: "jenkins/jenkins-jenkins-agent"
#         value: "true"
#       serverUrl: "https://kubernetes.default"
#       templates:
#       - containers:
#         - args: "^${computer.jnlpmac} ^${computer.name}"
#           command: "sleep"
#           envVars:
#           - envVar:
#               key: "JENKINS_URL"
#               value: "http://jenkins.jenkins.svc.cluster.local:8080/"
#           image: "jenkins/inbound-agent:4.11.2-4"
#           livenessProbe:
#             failureThreshold: 0
#             initialDelaySeconds: 0
#             periodSeconds: 0
#             successThreshold: 0
#             timeoutSeconds: 0
#           name: "jnlp"
#           resourceLimitCpu: "512m"
#           resourceLimitMemory: "512Mi"
#           resourceRequestCpu: "512m"
#           resourceRequestMemory: "512Mi"
#           workingDir: "/home/jenkins/agent"
#         id: "474be7705ac6cddeedf68ad2962972dd9921f64c6e534967402794fbf06a21ec"
#         label: "jenkins-jenkins-agent"
#         name: "default"
#         namespace: "jenkins"
#         nodeUsageMode: NORMAL
#         podRetention: "never"
#         serviceAccount: "default"
#         slaveConnectTimeout: 100
#         slaveConnectTimeoutStr: "100"
#         yamlMergeStrategy: "override"
#   crumbIssuer:
#     standard:
#       excludeClientIPFromCrumb: true
#   disableRememberMe: false
#   globalNodeProperties:
#   - envVars:
#       env:
#       - key: "OAUTH_CLIENT_SECRET"
#         value: "3b41ead62fbb8f77052c8ed1d0b3e1da6fccff38"
#   labelAtoms:
#   - name: "built-in"
#   - name: "jenkins-jenkins-agent"
#   markupFormatter: "plainText"
#   mode: NORMAL
#   myViewsTabBar: "standard"
#   numExecutors: 0
#   primaryView:
#     all:
#       name: "all"
#   projectNamingStrategy: "standard"
#   quietPeriod: 5
#   remotingSecurity:
#     enabled: true
#   scmCheckoutRetryCount: 0
#   securityRealm:
#     github:
#       clientID: "637496041a683f8c01c3"
#       clientSecret: "3b41ead62fbb8f77052c8ed1d0b3e1da6fccff38"
#       githubApiUri: "https://api.github.com"
#       githubWebUri: "https://github.com"
#       oauthScopes: "read:org,user:email,repo"
#   slaveAgentPort: 50000
#   systemMessage: "Welcome to my build server.\r\n\r\nThis Jenkins is 100% configured\
#     \ and managed 'as code'.\r\nConfig is now mostly handled by the 'Jenkins Configuration\
#     \ as Code' (JCasC) plugin."
#   updateCenter:
#     sites:
#     - id: "default"
#       url: "https://updates.jenkins.io/update-center.json"
#   views:
#   - all:
#       name: "all"
#   viewsTabBar: "standard"
# globalCredentialsConfiguration:
#   configuration:
#     providerFilter: "none"
#     typeFilter: "none"
# security:
#   apiToken:
#     creationOfLegacyTokenEnabled: false
#     tokenGenerationOnCreationEnabled: false
#     usageStatisticsEnabled: true
#   gitHooks:
#     allowedOnAgents: false
#     allowedOnController: false
#   gitHostKeyVerificationConfiguration:
#     sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
#   globalJobDslSecurityConfiguration:
#     useScriptSecurity: true
#   sSHD:
#     port: -1
# unclassified:
#   bitbucketEndpointConfiguration:
#     endpoints:
#     - bitbucketCloudEndpoint:
#         enableCache: false
#         manageHooks: false
#         repositoriesCacheDuration: 0
#         teamCacheDuration: 0
#   buildDiscarders:
#     configuredBuildDiscarders:
#     - "jobBuildDiscarder"
#   fingerprints:
#     fingerprintCleanupDisabled: false
#     storage: "file"
#   gitHubConfiguration:
#     apiRateLimitChecker: ThrottleForNormalize
#   gitHubPluginConfig:
#     hookUrl: "http://jenkins:8080/github-webhook/"
#   globalLibraries:
#     libraries:
#     - defaultVersion: "main"
#       name: "shared-library"
#       retriever:
#         modernSCM:
#           scm:
#             git:
#               credentialsId: "github-pwd"
#               id: "afedb203-f94a-4dce-a6b6-c52499e8a13a"
#               remote: "https://github.com/opeomotayo/cd-projects.git"
#               traits:
#               - "gitBranchDiscovery"
#   junitTestResultStorage:
#     storage: "file"
#   location:
#     adminAddress: "address not configured yet <nobody@nowhere>"
#     url: "http://jenkins:8080/"
#   mailer:
#     charset: "UTF-8"
#     useSsl: false
#     useTls: false
#   pollSCM:
#     pollingThreadCount: 10
#   scmGit:
#     addGitTagAction: false
#     allowSecondFetch: false
#     createAccountBasedOnEmail: false
#     disableGitToolChooser: false
#     hideCredentials: false
#     showEntireCommitSummaryInChanges: false
#     useExistingAccountWithSameEmail: false
#   sonarGlobalConfiguration:
#     buildWrapperEnabled: false
# tool:
#   git:
#     installations:
#     - home: "/usr/bin/git"
#       name: "git"
#   mavenGlobalConfig:
#     globalSettingsProvider: "standard"
#     settingsProvider: "standard"
#   sonarRunnerInstallation:
#     installations:
#     - name: "sonarqube"
#       properties:
#       - installSource:
#           installers:
#           - sonarRunnerInstaller:
#               id: "4.8.0.2856"

#   jobs:
#     - script: >
#         job('seed') {
#             scm {
#               git {
#                 extensions {
#                   wipeOutWorkspace()
#                 }
#                 remote {
#                   github('opeomotayo/cd-projects')
#                 }
#                 branches('main')
#               }
#             } 
#             triggers {
#               scm('H/15 * * * *')
#             }
#             steps {
#               jobDsl {
#                 targets('jobs/**/*.groovy')
#               }
#             }      
#         }
# security:
#   globalJobDslSecurityConfiguration:
#     useScriptSecurity: false

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "github-pwd"
          id: "github-pwd"
          password: "{AQAAABAAAAAQhYdt1NVqlXF10TsMHlCCZ51GnqH4Huj6p2W4Y9qZfuE=}"
          scope: GLOBAL
          username: "opeomotayo"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "jenkins"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          command: "sleep"
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.jenkins.svc.cluster.local:8080/"
          image: "jenkins/inbound-agent:4.11.2-4"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        id: "474be7705ac6cddeedf68ad2962972dd9921f64c6e534967402794fbf06a21ec"
        label: "jenkins-jenkins-agent"
        name: "default"
        namespace: "jenkins"
        nodeUsageMode: "NORMAL"
        podRetention: "never"
        serviceAccount: "default"
        slaveConnectTimeout: 100
        slaveConnectTimeoutStr: "100"
        yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  - name: "jenkins-jenkins-agent"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin
       - id: test
         password: test
  slaveAgentPort: 50000
  systemMessage: "Welcome to my build server.\r\n\r\nThis Jenkins is 100% configured\
    \ and managed 'as code'.\r\nConfig is now mostly handled by the 'Jenkins Configuration\
    \ as Code' (JCasC) plugin."
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://jenkins:8080/github-webhook/"
  globalLibraries:
    libraries:
    - defaultVersion: "main"
      name: "shared-library"
      retriever:
        modernSCM:
          scm:
            git:
              credentialsId: "github-pwd"
              id: "afedb203-f94a-4dce-a6b6-c52499e8a13a"
              remote: "https://github.com/opeomotayo/cd-projects.git"
              traits:
              - "gitBranchDiscovery"
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
  
  jobs:
  - script: >
      job('seed') {
          scm {
            git {
              extensions {
                wipeOutWorkspace()
              }
              remote {
                github('opeomotayo/cd-projects')
              }
              branches('main')
            }
          } 
          triggers {
            scm('H/15 * * * *')
          }
          steps {
            jobDsl {
              targets('jobs/*.groovy')
            }
          }      
      }
tool:
  git:
    installations:
    - home: "/usr/bin/git"
      name: "git"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  sonarRunnerInstallation:
    installations:
    - name: "sonarqube"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.8.0.2856"


