apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app1
  name: flask-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      containers:
      - image: opeomotayo/flask-app1:1
        name: flask-app1
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-app1
