apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-app-production
  namespace: blog-app
spec:
  secretName: blog-app-production-certificate
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - blog-app.opeomotayo.net
    
