---
# Source: portainer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa-clusteradmin
  namespace: default
  labels:
    helm.sh/chart: portainer-1.0.40
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "ce-latest-ee-2.17.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: portainer/templates/pvc.yaml
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: RELEASE-NAME-portainer
  namespace: default
  annotations:
    volume.alpha.kubernetes.io/storage-class: "generic"
  labels:
    io.portainer.kubernetes.application.stack: portainer
    helm.sh/chart: portainer-1.0.40
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "ce-latest-ee-2.17.1"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
# Source: portainer/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME-portainer
  labels:
    helm.sh/chart: portainer-1.0.40
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "ce-latest-ee-2.17.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: default
  name: portainer-sa-clusteradmin
---
# Source: portainer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-portainer
  namespace: default
  labels:
    io.portainer.kubernetes.application.stack: portainer
    helm.sh/chart: portainer-1.0.40
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "ce-latest-ee-2.17.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
      nodePort: 30777
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: https
      nodePort: 30779
    - port: 30776
      targetPort: 30776
      protocol: TCP
      name: edge
      nodePort: 30776
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: portainer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-portainer
  namespace: default
  labels:
    io.portainer.kubernetes.application.stack: portainer
    helm.sh/chart: portainer-1.0.40
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "ce-latest-ee-2.17.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app.kubernetes.io/name: portainer
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portainer
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      nodeSelector:
        {}
      serviceAccountName: portainer-sa-clusteradmin
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: RELEASE-NAME-portainer
      containers:
        - name: portainer
          image: "portainer/portainer-ce:2.17.1"
          imagePullPolicy: Always
          args:
          - '--tunnel-port=30776'
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
            - name: tcp-edge
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /
              port: 9443
              scheme: HTTPS
          resources:
            {}
---
# Source: portainer/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-ingress
  namespace: portainer
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - portainer.opeomotayo.net
    secretName: portainer-production-certificate
  rules:
  - host: portainer.opeomotayo.net
    http:
      paths:
      - backend:
          service:
            name: portainer-portainer-lts
            port:
              number: 9443
        path: /
        pathType: Prefix
---
# Source: portainer/templates/ingress.yaml
#managed by opeomotayo
---
# Source: portainer/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-portainer-test-connection"
  namespace: default  
  labels:
    helm.sh/chart: portainer-1.0.40
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "ce-latest-ee-2.17.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['RELEASE-NAME-portainer:9000']
  restartPolicy: Never
