# Playbook to call multiple roles to configure systems
- name: configure systems
  hosts: 167.235.236.197
  become: yes

  tasks:

- name: call roles
  hosts: 167.235.236.197
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
