# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 167.235.236.197
  become: yes

  tasks:

- name: Call Roles
  hosts: servers
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
