apiVersion: v2
name: zabbix-helm-chrt

description: A Helm chart for deploying Zabbix agent and proxy

home: https://www.zabbix.com/
icon: https://assets.zabbix.com/img/logo/zabbix_logo_500x131.png

type: application

version: 1.2.2
appVersion: trunk

dependencies:
- name: kube-state-metrics
  version: "3.5.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-state-metrics.enabled