#managed by opeomotayo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - nexus.opeomotayo.net
    secretName: nexus-production-certificate
  rules:
  - host: nexus.opeomotayo.net
    http:
      paths:
      - backend:
          service:
            name: nexus-nexus-iq-server
            port:
              number: 8070
        path: /
        pathType: Prefix
