def app
def DOCKERTAG

pipeline {
  options {
    skipStagesAfterUnstable()
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  
  agent {
    kubernetes {
      yamlFile 'build-pod.yaml'
      defaultContainer 'devops-tools'      
    }
  }

  parameters {
    string(defaultValue: "${env.BUILD_NUMBER}", description: 'The build number of the ci job', name: 'DOCKERTAG')
  }

  stages {
    stage('Clone repository') { 
      steps { 
        script {
          checkout scm
        }
      }
    }
    stage('Update GIT') {
      steps { 
        script {
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            withCredentials([usernamePassword(credentialsId: 'github-pat', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
              //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
              sh "echo DOCKERTAG is ${DOCKERTAG} or ${params.DOCKERTAG}"
              sh "git config --global user.email opeomotayo@gmail.com"
              sh "git config --global user.name opeomotayo"
              sh "git config --global --add safe.directory /home/jenkins/agent/workspace/flask-blog-cd"
              // sh "git switch main"
              sh "echo updating flask-blog app image"
              sh "cat technologies/cd-pipelines/flask-blog-cd/deployment.yaml"
              sh "sed -i 's+opeomotayo/flask-blog.*+opeomotayo/flask-blog:${params.DOCKERTAG}+g' technologies/cd-pipelines/flask-blog-cd/deployment.yaml"
              sh "cat technologies/cd-pipelines/flask-blog-cd/deployment.yaml"

              sh "echo updating mysql db image"
              sh "cat technologies/cd-pipelines/flask-blog-cd/stateful-set.yaml"
              sh "sed -i 's+opeomotayo/mysql-blog.*+opeomotayo/mysql-blog:${params.DOCKERTAG}+g' technologies/cd-pipelines/flask-blog-cd/stateful-set.yaml"
              sh "cat technologies/cd-pipelines/flask-blog-cd/stateful-set.yaml"

              sh "git add ."
              sh "git commit -m 'Done by Jenkins Job changemanifest: ${params.DOCKERTAG}'"
              sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/cd-projects.git HEAD:main"
            }
          }
        }
      }
    }
  }
}
