image:
  # Sonatype Official Public Image
  repository: opeomotayo/nexus3-github-oauth-plugin
  tag: 3.52.0

nexus:
  docker:
    enabled: true
    registries:
      - host: nexus.opeomotayo.net
        port: 5000
        secretName: nexus-production-certificate
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi
