image:
  # Sonatype Official Public Image
  repository: opeomotayo/nexus3-with-github-oauth-plugin
  tag: v1

persistence:
  enabled: true
  accessMode: ReadWriteMany

# nexus:
#   resources:
#     requests:
#       cpu: 2
#       memory: 4Gi
#     limits:
#       cpu: 4
#       memory: 8Gi
