def DOCKERTAG

pipeline {
  options {
    skipStagesAfterUnstable()
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  
  agent {
    kubernetes {
      yamlFile 'build-pod.yaml'
      defaultContainer 'devops-tools'      
    }
  }

  parameters {
    string(defaultValue: "${env.BUILD_NUMBER}", description: 'This defult to cd job number', name: 'DOCKERTAG')
  }

  stages {
    stage('Clone repository') { 
      steps { 
        script {
          checkout scm
        }
      }
    }
    stage('Update shop-api image') {
      steps { 
        script {
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            withCredentials([usernamePassword(credentialsId: 'github-pat', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
              //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
              sh "echo DOCKERTAG is ${DOCKERTAG} or ${params.DOCKERTAG}"
              sh "git config --global user.email opeomotayo@gmail.com"
              sh "git config --global user.name opeomotayo"
              sh "git config --global --add safe.directory /home/jenkins/agent/workspace/bookstore-cd/shopapi"
              // sh "git switch main"
              sh "cat technologies/cd-pipelines/bookstore-cd/shopapi/deployment.yaml"
              sh "sed -i 's+opeomotayo/shop-api.*+opeomotayo/shop-api:${params.DOCKERTAG}+g' technologies/cd-pipelines/bookstore-cd/shopapi/deployment.yaml"
              sh "cat technologies/cd-pipelines/bookstore-cd/shopapi/deployment.yaml"
              sh "git add ."
              sh "git commit -m 'Done by Jenkins Job changemanifest: ${params.DOCKERTAG}'"
              sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/cd-projects.git HEAD:main"
            }
          }
        }
      }
    }
    // stage('Update shop-ui image') {
    //   steps { 
    //     script {
    //       catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
    //         withCredentials([usernamePassword(credentialsId: 'github-pat', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
    //           //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
    //           sh "echo DOCKERTAG is ${DOCKERTAG} or ${params.DOCKERTAG}"
    //           sh "git config --global user.email opeomotayo@gmail.com"
    //           sh "git config --global user.name opeomotayo"
    //           sh "git config --global --add safe.directory /home/jenkins/agent/workspace/bookstore-cd/shopui"
    //           // sh "git switch main"
    //           sh "cat technologies/cd-pipelines/bookstore-cd/shopapi/deployment.yaml"
    //           sh "sed -i 's+opeomotayo/shop-ui.*+opeomotayo/shop-ui:${params.DOCKERTAG}+g' technologies/cd-pipelines/bookstore-cd/shopui/deployment.yaml"
    //           sh "cat technologies/cd-pipelines/bookstore-cd/shopui/deployment.yaml"
    //           sh "git add ."
    //           sh "git commit -m 'Done by Jenkins Job changemanifest: ${params.DOCKERTAG}'"
    //           sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/cd-projects.git HEAD:main"
    //         }
    //       }
    //     }
    //   }
    // }
    // stage('Update website image') {
    //   steps { 
    //     script {
    //       catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
    //         withCredentials([usernamePassword(credentialsId: 'github-pat', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
    //           //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
    //           sh "echo DOCKERTAG is ${DOCKERTAG} or ${params.DOCKERTAG}"
    //           sh "git config --global user.email opeomotayo@gmail.com"
    //           sh "git config --global user.name opeomotayo"
    //           sh "git config --global --add safe.directory /home/jenkins/agent/workspace/bookstore-cd/website"
    //           // sh "git switch main"
    //           sh "cat technologies/cd-pipelines/bookstore-cd/website/deployment.yaml"
    //           sh "sed -i 's+opeomotayo/website.*+opeomotayo/website:${params.DOCKERTAG}+g' technologies/cd-pipelines/bookstore-cd/website/deployment.yaml"
    //           sh "cat technologies/cd-pipelines/bookstore-cd/website/deployment.yaml"
    //           sh "git add ."
    //           sh "git commit -m 'Done by Jenkins Job changemanifest: ${params.DOCKERTAG}'"
    //           sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/cd-projects.git HEAD:main"
    //         }
    //       }
    //     }
    //   }
    // }
  }
}