#managed by opeomotayo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube-ingress
  namespace: sonarqube
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - sonarqube.opeomotayo.net
    secretName: sonarqube-production-certificate
  rules:
  - host: sonarqube.opeomotayo.net
    http:
      paths:
      - backend:
          service:
            name: sonarqube-lts-sonarqube

            port:
              number: 9000
        path: /
        pathType: Prefix
