global:
  ingress:
    enabled: true

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.opeomotayo.net
    path: "/"
    tls:
      - hosts:
          - alertmanager.opeomotayo.net
        secretName: alertmanager-production-certificate

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.opeomotayo.net
    path: "/"
    tls:
      - hosts:
          - grafana.opeomotayo.net
        secretName: grafana-production-certificate


prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.opeomotayo.net
    path: "/"
    tls:
      - hosts:
          - prometheus.opeomotayo.net
        secretName: prometheus-production-certificate