---
apiVersion: v1
kind: Service
metadata:
  name: flask-blog
  namespace: blog-app
  labels:
    app: flask-app  
spec:
  selector:
    type: blog
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: blog-app
  labels:
    app: flask-app    
spec:
  ports:
    - port: 3306
  selector:
    db: mysql-instance
  clusterIP: None
