ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  metadata:
    name: sonarqube-lts
    labels:
      app: sonarqube-lts
      chart: sonarqube-lts-1.0.31
      release: sonarqube-lts
      heritage: Helm
  spec:
    rules:
    - host: sonarqube.opeomotayo.net
      http:
        paths:
        - backend:
            service:
              name: sonarqube-lts
              port:
                number: 9000
          path: /
          pathType: ImplementationSpecific
        tls:
        - hosts:
          - sonarqube.opeomotayo.net
          secretName: sonarqube-production-certificate

  # ingress:
  #   enabled: false 
  #   paths:
  #   - path: "/"
  #     pathType: Prefix
  #     backend:
  #       service:
  #         name: >-
  #           jenkins
  #         port:
  #           number: 8080
  #   apiVersion: "networking.k8s.io/v1"
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #   # configures the hostname e.g. jenkins.example.com
  #   hostName: jenkins.opeomotayo.net
  #   tls:
  #   - hosts:
  #     - jenkins.opeomotayo.net
  #     secretName: jenkins-production-certificate

