controller:
  additionalPlugins:
    - blueocean
    - job-dsl
  
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
      pipelines-jobs: |
        jobs:
          - script: >
              multibranchPipelineJob('multibranch-pipeline-job') {
                branchSources {
                  git {
                    id('123456789') // IMPORTANT: use a constant and unique identifier
                    remote('https://github.com/jenkinsci/job-dsl-plugin.git')
                  }
                }
              }
          - script: >
              pipelineJob('actions-runner-controller') {
                definition {
                  cpsScm {
                    scm {
                      git('https://github.com/opeomotayo/cd-projects.git')
                      scriptPath('jobs/actions-runner-controller/Jenkinsfile')
                    } 
                  } 
                }  
              }          
          - script: >
              pipelineJob('github-demo') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          github('jenkinsci/pipeline-examples')
                        }
                      }
                    }   
                    scriptPath('declarative-examples/simple-examples/environmentInStage.groovy')
                  }  
                }       
              }
      #sidecars:
      #configAutoReload:
      #enabled: true
      #folder: >-
      # https://raw.githubusercontent.com/opeomotayo/cd-projects/main/technologies/charts/jenkins/ci/jenkins-casc.yaml

  ingress:
    enabled: false #I chanaged it to false because I created ingress.yaml in the template folder
    paths:
    - path: "/"
      pathType: Prefix
      backend:
        service:
          name: >-
            jenkins
          port:
            number: 8080
    apiVersion: "networking.k8s.io/v1"
    annotations:
      kubernetes.io/ingress.class: nginx
    # configures the hostname e.g. jenkins.example.com
    hostName: jenkins.opeomotayo.net
    tls:
    - hosts:
      - jenkins.opeomotayo.net
      secretName: jenkins-production-certificate
