# agent:
#   resources:
#     requests:
#       cpu: "256m"
#       memory: "256Mi"
#     limits:
#       cpu: "512m"
#       memory: "512Mi"    

# controller:
  # jenkinsUrl: "https://jenkins.opeomotayo.net"
  # image: "jenkins/jenkins"
  # tag: "2.389-jdk11"

  # # adminSecret: false
  # # resources:
  # #   requests:
  # #     cpu: "25m"
  # #     memory: "128Mi"
  # #   limits:
  # #     cpu: "2000m"
  # #     memory: "4096Mi"

  # # sidecars:
  # #   configAutoReload:
  # #     resources:
  # #       limits:
  # #         cpu: 100m
  # #         memory: 100Mi
  # #       requests:
  # #         cpu: 25m
  # #         memory: 25Mi
  
  # installPlugins:
  #   - configuration-as-code
  #   - git
  #   - kubernetes
  #   - workflow-aggregator

  # additionalPlugins:
  #   - blueocean
  #   - credentials-binding
  #   - github-oauth
  #   - job-dsl
  #   - kubernetes-credentials-provider
  #   - ldap
  #   - nexus-artifact-uploader
  #   - matrix-auth
  #   - role-strategy
  #   # - slack
  #   - sonar

  # unclassified:
  #   globalLibraries:
  #     libraries:
  #       - name: "shared-library"
  #         retriever:
  #           modernSCM:
  #             scm:
  #               git:
  #                 remote: "https://github.com/opeomotayo/cd-projects.git"
  #                 credentialsId: '${github-pat}'

  # tool:
  #   git:
  #     installations:
  #     - home: "/usr/bin/git"
  #       name: "git"
  #   sonarRunnerInstallation:
  #     installations:
  #     - name: "sonarqube"
  #       properties:
  #       - installSource:
  #           installers:
  #           - sonarRunnerInstaller:
  #               id: "4.8.0.2856" 
  
  # # url('https://github.com/opeomotayo/cd-projects.git')
  # # credentials('ssh-key-jenkins-github-devops')
  # # security-realm: |
  # #   jenkins:
  # #     securityRealm:
  # #       github:
  # #         clientID: "bc7a747c92713d3c6f9d"
  # #         clientSecret: "${oauth-client-secret}"
  # #         githubApiUri: "https://api.github.com"
  # #         githubWebUri: "https://github.com"
  # #         oauthScopes: "read:org,user:email,repo"
  # #     authorizationStrategy:
  # #       globalMatrix:
  # #         permissions:
  #     #         - "GROUP:Overall/Administer:authenticated"
  # JCasC:
  #   enabled: true
  #   defaultConfig: false
  #   configScripts:
  #     welcome-message: |
  #       jenkins:
  #         systemMessage: |
  #           Welcome to my build server.

  #           This Jenkins is 100% configured and managed 'as code'.
  #           Config is now mostly handled by the 'Jenkins Configuration as Code' (JCasC) plugin.

  #     pipelines-jobs: |
  #       jobs:
  #         - script: >
  #             multibranchPipelineJob('multibranch-pipeline-job') {
  #               branchSources {
  #                 git {
  #                   id('123456789') // IMPORTANT: use a constant and unique identifier
  #                   remote('https://github.com/jenkinsci/job-dsl-plugin.git')
  #                 }
  #               }
  #             } 
  #         - script: >
  #             pipelineJob('actions-runner-controller') {
  #             logRotator {
  #                 numToKeep(10)
  #                 daysToKeep(30)
  #             }
  #               definition {
  #                 cpsScm {
  #                   scm {
  #                     git {
  #                       remote {
  #                         github('opeomotayo/cd-projects')
  #                       }
  #                       branches('main')
  #                     }
  #                   }   
  #                   scriptPath('jobs/actions-runner-controller/Jenkinsfile')
  #                 }  
  #               }       
  #             }
  #         - script: >
  #             pipelineJob('actions-runner-controller2') {
  #               logRotator {
  #                 numToKeep(10)
  #                 daysToKeep(30)
  #               }
  #               definition {
  #                 cpsScm {
  #                   scm {
  #                       git {
  #                         remote {
  #                             url('https://github.com/opeomotayo/cd-projects.git')
  #                         }
  #                         branches('*')
  #                       }
  #                   }
  #                   scriptPath('jobs/actions-runner-controller/Jenkinsfile')
  #                 }
  #               }         
  #             }   
  #         - script: >
  #             pipelineJob('github-demo') {
  #               definition {
  #                 cpsScm {
  #                   scm {
  #                     git {
  #                       remote {
  #                         github('jenkinsci/pipeline-examples')
  #                       }
  #                     }
  #                   }   
  #                   scriptPath('declarative-examples/simple-examples/environmentInStage.groovy')
  #                 }  
  #               }       
  #             }
  sidecars:
    configAutoReload:
      folder: >-
        https://raw.githubusercontent.com/opeomotayo/cd-projects/main/technologies/charts/jenkins/ci/jenkins-casc.yaml

