agent:
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"

backup:
  enabled: false
  resources:
    requests:
      memory: "256m"
      cpu: "256m"
    limits:
      memory: "512m"
      cpu: "512m" 

controller:
  image: "jenkins/jenkins"
  tag: "lts-jdk11"

  servicePort: 8080
  targetPort: 8080

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "2048Mi"

  initContainerResources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "2048Mi"
  numExecutors: 1

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.opeomotayo.net
    # paths: "/"
    tls:
      - secretName: jenkins-production-certificate
        hosts:
          - jenkins.opeomotayo.net

  # secretEnvVars:
  # - key: clientSecret
  #   secretKey: clientSecret
  #   secretName: github-oauth
  # containerEnv:
  # - name: clientID
  #   valueFrom:
  #   secretKeyRef:
  #     name: github-oauth
  #     key: clientID
  # - name: clientSecret
  #   valueFrom:
  #   secretKeyRef:
  #     name: github-oauth
  #     key: clientSecret

  installPlugins:
    - configuration-as-code
    - git
    - kubernetes #:3802.vb_b_600831fcb_3
    - workflow-aggregator
  additionalPlugins:
    - blueocean
    - credentials-binding
    - docker-build-step
    - docker-plugin
    - docker-workflow
    - github-oauth
    - github-pullrequest
    - job-dsl
    - kubernetes-cli #:1.11.0
    - kubernetes-credentials #:0.10.0
    - kubernetes-credentials-provider #:1.208.v128ee9800c04
    - kubernetes-client-api #:6.3.1-206.v76d3b_6b_14db_b
    - ldap
    - nexus-artifact-uploader
    - matrix-auth
    - parameterized-trigger
    - role-strategy
    - slack
    - sonar

  sidecars:
    configAutoReload:
      folder: >-
        https://raw.githubusercontent.com/opeomotayo/cd-projects/main/technologies/charts/jenkins/ci/jenkins-casc.yaml

