controller:
  # tag: "2.235.1"
  ingress:
    enabled: true
    paths:
    - path: "/"
      pathType: Prefix
      backend:
        service:
          name: >-
            {{ template "jenkins.fullname" . }}
          port:
            number: 8080
    apiVersion: "networking.k8s.io/v1"
    annotations:
      kubernetes.io/ingress.class: nginx
    # configures the hostname e.g. jenkins.example.com
    hostName: jenkins.opeomotayo.net
    tls:
    - hosts:
      - jenkins.opeomotayo.net
      secretName: jenkins-production-certificate

  additionalPlugins:
    - blueocean
    - job-dsl

  # sidecars:
  #   configAutoReload:
  #     folder: >-
  #       https://github.com/opeomotayo/ci-projects/blob/main/README.md

  # persistence:
  #   enabled: true
  #   existingClaim: jenkins-claim
