# agent:
#   resources:
#     requests:
#       cpu: "256m"
#       memory: "256Mi"
#     limits:
#       cpu: "512m"
#       memory: "512Mi"    

controller:
  image: "jenkins/jenkins"
  tag: "lts-jdk11"
  numExecutors: 1
  javaOpts: >
    -Dpermissive-script-security.enabled=true
    -Djenkins.install.runSetupWizard=false
    - configuration-as-code
    - git
    - kubernetes
    - workflow-aggregator
  additionalPlugins:
    - blueocean
    - credentials-binding
    - github-oauth:0.39
    - job-dsl
    - kubernetes-credentials-provider
    - ldap
    - nexus-artifact-uploader
    - matrix-auth
    - role-strategy
    # - slack
    - sonar
    - permissive-script-security:0.7

  sidecars:
    configAutoReload:
      folder: >-
        https://raw.githubusercontent.com/opeomotayo/cd-projects/main/technologies/charts/jenkins/ci/jenkins-casc.yaml

