# agent:
#   resources:
#     requests:
#       cpu: "256m"
#       memory: "256Mi"
#     limits:
#       cpu: "512m"
#       memory: "512Mi"    

controller:
  image: "jenkins/jenkins"
  tag: "lts-jdk11"
  numExecutors: 1
  secretEnvVars:
  - key: clientSecret
    secretKey: clientSecret
    secretName: github-oauth
  - key: clientID
    secretKey: clientID
    secretName: github-oauth
  # containerEnv:
  # - name: clientID
  #   valueFrom:
  #   secretKeyRef:
  #     name: github-oauth
  #     key: clientID
  # - name: clientSecret
  #   valueFrom:
  #   secretKeyRef:
  #     name: github-oauth
  #     key: clientSecret
  installPlugins:
    - configuration-as-code
    - git
    - kubernetes
    - workflow-aggregator
  additionalPlugins:
    - blueocean
    - credentials-binding
    - github-oauth:0.39
    - job-dsl
    - kubernetes-credentials-provider
    - ldap
    - nexus-artifact-uploader
    - matrix-auth
    - role-strategy
    # - slack
    - sonar


  sidecars:
    configAutoReload:
      folder: >-
        https://raw.githubusercontent.com/opeomotayo/cd-projects/main/technologies/charts/jenkins/ci/jenkins-casc.yaml

