controller:
  jenkinsUrl: "https://jenkins.opeomotayo.net"
  image: "jenkins/jenkins"
  tag: "2.389-jdk11"
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  additionalPlugins:
    - blueocean
    - job-dsl
    - credentials-binding
    - kubernetes-credentials-provider
  
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: |
            Welcome to my build server.

            This Jenkins is 100% configured and managed 'as code'.
            Config is now mostly handled by the 'Jenkins Configuration as Code' (JCasC) plugin.
      pipelines-jobs: |
        jobs:
          - script: >
              multibranchPipelineJob('multibranch-pipeline-job') {
                branchSources {
                  git {
                    id('123456789') // IMPORTANT: use a constant and unique identifier
                    remote('https://github.com/jenkinsci/job-dsl-plugin.git')
                  }
                }
              } 
          - script: >
              pipelineJob('actions-runner-controller') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          github('opeomotayo/cd-projects')
                        }
                      }
                    }   
                    scriptPath('jobs/actions-runner-controller/Jenkinsfile')
                  }  
                }       
              }      
          - script: >
              pipelineJob('github-demo') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          github('jenkinsci/pipeline-examples')
                        }
                      }
                    }   
                    scriptPath('declarative-examples/simple-examples/environmentInStage.groovy')
                  }  
                }       
              }
      #sidecars:
      #configAutoReload:
      #enabled: true
      #folder: >-
      # https://raw.githubusercontent.com/opeomotayo/cd-projects/main/technologies/charts/jenkins/ci/jenkins-casc.yaml

#disabled ingress here because I created ingress.yaml in the template folder
  # ingress:
  #   enabled: false 
  #   paths:
  #   - path: "/"
  #     pathType: Prefix
  #     backend:
  #       service:
  #         name: >-
  #           jenkins
  #         port:
  #           number: 8080
  #   apiVersion: "networking.k8s.io/v1"
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #   # configures the hostname e.g. jenkins.example.com
  #   hostName: jenkins.opeomotayo.net
  #   tls:
  #   - hosts:
  #     - jenkins.opeomotayo.net
  #     secretName: jenkins-production-certificate

