apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: html-blog
  namespace: html-blog
  labels:
    app: html-blog
spec:
  selector:
    # Selector for Pods
    app: html-blog
  ports:
    # Port Map
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
