pipeline {
  options {
    skipStagesAfterUnstable()
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }
  
  agent {
    kubernetes {
      yamlFile 'build-pod.yaml'
      defaultContainer 'devops-tools'      
    }
  }
  stages {
    stage('Clone repository') { 
      steps { 
        script {
          checkout scm
        }
      }
    }
    stage('Update GIT') {
      steps { 
        script {
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            withCredentials([usernamePassword(credentialsId: 'github-pat', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
              //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
              sh "git config --global user.email opeomotayo@gmail.com"
              sh "git config --global user.name opeomotayo"
              sh "git config --global --add safe.directory /home/jenkins/agent/workspace/todo-app-update-tag"
              // sh "git switch main"
              sh "cat technologies/deployment-pipelines/deployment.yaml"
              sh "sed -i 's+opeomotayo/todo-app.*+opeomotayo/todo-app:${params.DOCKERTAG}+g' technologies/deployment-pipelines/deployment.yaml"
              sh "cat technologies/deployment-pipelines/deployment.yaml"
              sh "git add ."
              sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
              sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/cd-projects.git HEAD:main"
            }
          }
        }
      }
    }
  }
}