apiVersion: v1
kind: PersistentVolume
metadata:
  name: rsyslog-pv
  labels:
    type: local-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: "/data/rsyslog-pv"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - poc-server
