apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsyslog-pvc
  namespace: rsyslog
  labels:
    type: local-pvc
spec:
  storageClassName: local-path
  volumeName: "rsyslog-pv" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
