apiVersion: v1
kind: Service
metadata:
  name: "rsyslog-service"
  namespace: "rsyslog"
spec:
  ports:
    - name: tcp
      port: 514
      targetPort: 514
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "rsyslog"