#managed by opeomotayo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbix-ingress
  namespace: zabbix
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - zabbix.opeomotayo.net
    secretName: zabbix-production-certificate
  rules:
  - host: zabbix.opeomotayo.net
    http:
      paths:
      - backend:
          service:
            name: zabbix
            port:
              number: 80
        path: /
        pathType: Prefix
