apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-production
  namespace: portainer
spec:
  secretName: portainer-production-certificate
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - portainer.opeomotayo.net
    
