zabbixweb:
  service:
    # -- Type of service for Zabbix web
    type: ClusterIP
    # -- Port to expose service
    port: 80
    # -- Port of application pod
    # targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: zabbix.opeomotayo.net
      paths: 
        - "/"

  tls:
    - secretName: zabbix-production-certificate
      hosts:
        - zabbix.opeomotayo.net