apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: jenkins
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: 'https://github.com/opeomotayo/cd-projects.git'
    path: technologies/charts/jenkins
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-override.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
