service:
  type: ClusterIP
  httpsPort: 9443
  edgePort: 8000

ingress:
  enabled: true

tls:
  # If set, Portainer will be configured to use TLS only
  force: true

persistence:
  enabled: true
  size: "5Gi"