apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-pat
  namespace: jenkins
spec:
  encryptedData:
    password: AgByQDmSQKeG+NhuWIltf6rS17HrSvUFmsDzDCWNL2NINmzMDH+Yo4Q4TD9PgfpX9eLrsK5hiAxk2yZFdPjxsXSM05QhaqipJHrg1ncpd3LI3SYiY73IB26szhXvmAWBq1GRdLzb2uqA/1v8vjp0OrrwBbARHfe+Scf5+fHWucM/+6gbmvsXMR8R1XUQJMdjtVIrQRuzjGYDRMAD0tGGIVowTwVt6dQybzuXBNoG3J9Mzu62u0hb2A6+GLv/g2Wkq2ZYfsxj0xwqFNhgXK2KSGJk8OAgMxmKJNVbmA+v/YHFdFra1t6wnrygEJwEzjJ/7lpi+bmDjQ3Pw7OCS3BqIN9gmgTgJPQu2ZiMts4U5dkoYWX9pTfbkl5pB24g+KYQjXAcmHJYb7XCTdlyzG+ClFpZcsndaKvwqi3xk1KihgczVmLGvaeCHBCGjOqjNl1yoVhLDu5iCp4lNp2bC3NTUKmyBFfrnWYNjQGh7FkC7FIGhaRiOcHrO6atYuPHF2PQkpj0B2sx9CONVI1RfVetK8P9EFJC4DIvTiR0G0eWpubmobnSVtvFLhAFXTy5LQgM+mvi5TecZPmNI3A2HV4s/e2xZYyhvgicNjuS3O6PzCqoaeSxSOWWgH9xBl3ytH4P+k5sQzDvEl502WHqWsBQlOwKUUoHHs2+xuFROPfcR+C6PR+k3lI0ZOxqXzaHpKwCS/ulvqPPliEak2qn+hMt1+EK6EyFgYUTbPuBMEp6Bd37qTk6udo1bC8j
    username: AgA5I7aasMilB8xOy0XVoy7hUbiULEdc7vUsr4AH9lmkCV/4fd6ocdukOcSlHw8WGPrXatvgVwdgnTZLxhfHTxan2itAGToFVd3Hf0ndFYmZuyqN/w9x8dHkUZfXwFH7b0axKAg0WxlllZBK4cVKJNEQyLOkTNPLWRpU2bBHRnD0iKlVhEkdCNPNxZLgQVJ2PyOhs3idIRDpKRDkXq96FzjTLSl0Fx2cZm0Erey79xG3LYPh7POVeqC+rmg3EGQz1F/xMxKBxPgnrZgc0YkLl8IedeSRbAfDJnvX/60tbDDfZcbLGYDR6L6Jr3u5K+yZg2UR0/c/BV5oT0h8UT60BV1UCbh15rPNxQh69WzTr7pHbkLr6Y0yn8xGmrRCUOnQ4EJ6Cj01z40zsxj2hDKEqQ7+UXWg7IBVL23cX4dikRvn4Borjzt19bYl3YStHfg01mXv2pnAKnRXecWjnj4PC+3mGtW3EHa/pR4mco66YbfMYIMchajOZgMJ9jk6E4Pkt5/d93bOkze4GkxNm6H8s4cPRIZLUk+TBfNHgY+6Y42F77vT3Mk6ZcyOaTeQFMJ1QWRJfyWOqGffsFOyN9dFVbA3QQGyp+/GwQuqYoSSrrlaKiEGCHh2F8rQMxzM1q6vfPV9rzd1RZOoUaLKmB6qjmdnCeEYjIK97UFS6ZNLzYO9bXxlq2XAdh7a4Zw2nzK7gf38oypqg+pahlgL
  template:
    data: null
    metadata:
      annotations:
        jenkins.io/credentials-description: github-pat credentials from Kubernetes
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: github-pat
      namespace: jenkins
    type: Opaque

